Import FastF1

In [ ]:
import pandas as pd
import fastf1
from pathlib import Path


project_root = Path.cwd().parent

cache_dir = project_root / "data" / "cache" / "fastf1"

cache_dir.mkdir(parents=True, exist_ok=True)

fastf1.Cache.enable_cache(str(cache_dir))

print(f"Project root: {project_root}")
print(f"Cache path: {cache_dir.resolve()}")
print(f"Cache exists: {cache_dir.exists()}")

#time format(min:sec.ms)
def format_time(value):
    if pd.isna(value):
        return None

    total_ms = round(value.total_seconds() * 1000)

    minutes, remainder = divmod(total_ms, 60_000)
    seconds, milliseconds = divmod(remainder, 1_000)

    return f"{minutes}:{seconds:02d}.{milliseconds:03d}"

Project root: c:\Users\umutnevzat.kahraman\Desktop\f1-pit-strategy-optimizer
Cache path: C:\Users\umutnevzat.kahraman\Desktop\f1-pit-strategy-optimizer\data\cache\fastf1
Cache exists: True

Get the race(2024 Italian GP)

In [52]:
session = fastf1.get_session(2024, "Italian Grand Prix", "R") 

session.load(
    telemetry=False,
    weather=True,
    messages=False
)

session.event

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for weather_data
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

RoundNumber                                                   16
Country                                                    Italy
Location                                                   Monza
OfficialEventName    FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2024
EventDate                                    2024-09-01 00:00:00
EventName                                     Italian Grand Prix
EventFormat                                         conventional
Session1                                              Practice 1
Session1Date                           2024-08-30 13:30:00+02:00
Session1DateUtc                              2024-08-30 11:30:00
Session2                                              Practice 2
Session2Date                           2024-08-30 17:00:00+02:00
Session2DateUtc                              2024-08-30 15:00:00
Session3                                              Practice 3
Session3Date                           2024-08-31 12:30:00+02:00
Session3DateUtc                              2024-08-31 10:30:00
Session4                                              Qualifying
Session4Date                           2024-08-31 16:00:00+02:00
Session4DateUtc                              2024-08-31 14:00:00
Session5                                                    Race
Session5Date                           2024-09-01 15:00:00+02:00
Session5DateUtc                              2024-09-01 13:00:00
F1ApiSupport                                                True
Name: 16, dtype: object

Get the columns for the race

In [53]:
print("Result Columns:")
print(session.results.columns.tolist())

print("\nLap Columns:")
print(session.laps.columns.tolist())

Result Columns:
['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName', 'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName', 'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition', 'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps']

Lap Columns:
['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime', 'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason', 'FastF1Generated', 'IsAccurate']

In [54]:
results_summary = session.results[
    ["Abbreviation", "TeamName", "GridPosition", "Position", "Status"]
]

results_summary

   Abbreviation         TeamName  GridPosition  Position    Status
16          LEC          Ferrari           4.0       1.0  Finished
81          PIA          McLaren           2.0       2.0  Finished
4           NOR          McLaren           1.0       3.0  Finished
55          SAI          Ferrari           5.0       4.0  Finished
44          HAM         Mercedes           6.0       5.0  Finished
1           VER  Red Bull Racing           7.0       6.0  Finished
63          RUS         Mercedes           3.0       7.0  Finished
11          PER  Red Bull Racing           8.0       8.0  Finished
23          ALB         Williams           9.0       9.0  Finished
20          MAG     Haas F1 Team          13.0      10.0  Finished
14          ALO     Aston Martin          11.0      11.0  Finished
43          COL         Williams          18.0      12.0  Finished
3           RIC               RB          12.0      13.0  Finished
31          OCO           Alpine          15.0      14.0    Lapped
10          GAS           Alpine          14.0      15.0    Lapped
77          BOT      Kick Sauber          19.0      16.0    Lapped
27          HUL     Haas F1 Team          10.0      17.0    Lapped
24          ZHO      Kick Sauber          20.0      18.0    Lapped
18          STR     Aston Martin          17.0      19.0    Lapped
22          TSU               RB          16.0      20.0   Retired

In [55]:
leclerc_laps = session.laps.pick_drivers("LEC")[
    ["Stint", "LapNumber", "LapTime", "Position", "Compound", "TyreLife", "PitInTime", "PitOutTime", "TrackStatus", "IsAccurate"]
]

leclerc_laps

,Stint,LapNumber,LapTime,Position,Compound,TyreLife,PitInTime,PitOutTime,TrackStatus,IsAccurate
0,1.0,1.0,0 days 00:01:28.179000,2.0,MEDIUM,1.0,NaT,NaT,1,False
1,1.0,2.0,0 days 00:01:25.396000,2.0,MEDIUM,2.0,NaT,NaT,1,True
2,1.0,3.0,0 days 00:01:25.179000,2.0,MEDIUM,3.0,NaT,NaT,1,True
3,1.0,4.0,0 days 00:01:24.810000,2.0,MEDIUM,4.0,NaT,NaT,1,True
4,1.0,5.0,0 days 00:01:24.603000,2.0,MEDIUM,5.0,NaT,NaT,1,True
5,1.0,6.0,0 days 00:01:24.663000,2.0,MEDIUM,6.0,NaT,NaT,1,True
6,1.0,7.0,0 days 00:01:24.434000,2.0,MEDIUM,7.0,NaT,NaT,1,True
7,1.0,8.0,0 days 00:01:24.569000,2.0,MEDIUM,8.0,NaT,NaT,1,True
8,1.0,9.0,0 days 00:01:24.362000,2.0,MEDIUM,9.0,NaT,NaT,1,True
9,1.0,10.0,0 days 00:01:24.432000,2.0,MEDIUM,10.0,NaT,NaT,1,True
10,1.0,11.0,0 days 00:01:24.846000,2.0,MEDIUM,11.0,NaT,NaT,1,True
11,1.0,12.0,0 days 00:01:24.916000,2.0,MEDIUM,12.0,NaT,NaT,1,True
12,1.0,13.0,0 days 00:01:25.529000,2.0,MEDIUM,13.0,NaT,NaT,1,True
13,1.0,14.0,0 days 00:01:25.606000,2.0,MEDIUM,14.0,NaT,NaT,1,True
14,1.0,15.0,0 days 00:01:30.192000,3.0,MEDIUM,15.0,0 days 01:17:08.772000,NaT,1,False
15,2.0,16.0,0 days 00:01:44.888000,7.0,HARD,1.0,NaT,0 days 01:17:33.191000,1,False
16,2.0,17.0,0 days 00:01:24.270000,6.0,HARD,2.0,NaT,NaT,1,True
17,2.0,18.0,0 days 00:01:23.875000,6.0,HARD,3.0,NaT,NaT,1,True
18,2.0,19.0,0 days 00:01:24.203000,6.0,HARD,4.0,NaT,NaT,1,True
19,2.0,20.0,0 days 00:01:23.826000,5.0,HARD,5.0,NaT,NaT,1,True
20,2.0,21.0,0 days 00:01:23.880000,5.0,HARD,6.0,NaT,NaT,1,True
21,2.0,22.0,0 days 00:01:23.768000,5.0,HARD,7.0,NaT,NaT,1,True
22,2.0,23.0,0 days 00:01:23.864000,3.0,HARD,8.0,NaT,NaT,1,True
23,2.0,24.0,0 days 00:01:23.640000,3.0,HARD,9.0,NaT,NaT,1,True
24,2.0,25.0,0 days 00:01:23.590000,3.0,HARD,10.0,NaT,NaT,1,True
25,2.0,26.0,0 days 00:01:23.321000,3.0,HARD,11.0,NaT,NaT,1,True
26,2.0,27.0,0 days 00:01:23.534000,3.0,HARD,12.0,NaT,NaT,1,True
27,2.0,28.0,0 days 00:01:23.284000,3.0,HARD,13.0,NaT,NaT,1,True
28,2.0,29.0,0 days 00:01:23.229000,3.0,HARD,14.0,NaT,NaT,1,True
29,2.0,30.0,0 days 00:01:23.359000,3.0,HARD,15.0,NaT,NaT,1,True
30,2.0,31.0,0 days 00:01:23.972000,3.0,HARD,16.0,NaT,NaT,1,True
31,2.0,32.0,0 days 00:01:23.274000,2.0,HARD,17.0,NaT,NaT,1,True
32,2.0,33.0,0 days 00:01:23.226000,2.0,HARD,18.0,NaT,NaT,1,True
33,2.0,34.0,0 days 00:01:23.430000,2.0,HARD,19.0,NaT,NaT,1,True
34,2.0,35.0,0 days 00:01:23.681000,2.0,HARD,20.0,NaT,NaT,1,True
35,2.0,36.0,0 days 00:01:23.714000,2.0,HARD,21.0,NaT,NaT,1,True
36,2.0,37.0,0 days 00:01:23.550000,2.0,HARD,22.0,NaT,NaT,1,True
37,2.0,38.0,0 days 00:01:23.624000,2.0,HARD,23.0,NaT,NaT,1,True
38,2.0,39.0,0 days 00:01:23.718000,1.0,HARD,24.0,NaT,NaT,1,True
39,2.0,40.0,0 days 00:01:23.690000,1.0,HARD,25.0,NaT,NaT,1,True
40,2.0,41.0,0 days 00:01:23.611000,1.0,HARD,26.0,NaT,NaT,1,True
41,2.0,42.0,0 days 00:01:23.670000,1.0,HARD,27.0,NaT,NaT,1,True
42,2.0,43.0,0 days 00:01:23.867000,1.0,HARD,28.0,NaT,NaT,1,True
43,2.0,44.0,0 days 00:01:23.430000,1.0,HARD,29.0,NaT,NaT,1,True
44,2.0,45.0,0 days 00:01:23.731000,1.0,HARD,30.0,NaT,NaT,1,True
45,2.0,46.0,0 days 00:01:23.597000,1.0,HARD,31.0,NaT,NaT,1,True
46,2.0,47.0,0 days 00:01:23.676000,1.0,HARD,32.0,NaT,NaT,1,True
47,2.0,48.0,0 days 00:01:23.518000,1.0,HARD,33.0,NaT,NaT,1,True
48,2.0,49.0,0 days 00:01:23.467000,1.0,HARD,34.0,NaT,NaT,1,True
49,2.0,50.0,0 days 00:01:23.461000,1.0,HARD,35.0,NaT,NaT,1,True
50,2.0,51.0,0 days 00:01:23.555000,1.0,HARD,36.0,NaT,NaT,1,True
51,2.0,52.0,0 days 00:01:23.750000,1.0,HARD,37.0,NaT,NaT,1,True
52,2.0,53.0,0 days 00:01:23.268000,1.0,HARD,38.0,NaT,NaT,1,True